name: Automated Backups Cryptovoxels
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16.3.0'
      - name: npm install
        run: |
          npm install -g arkb
      - name: Run Backups
        run: |
          node -v ; 
          arkb -v ;
          echo "Downloading map info..." ;
          curl -s 'https://www.cryptovoxels.com/api/parcels.json' > CryptoVoxelsArchive/parcels.json ;
          curl -s 'https://www.cryptovoxels.com/api/suburbs.json' > CryptoVoxelsArchive/suburbs.json ;
          curl -s 'https://www.cryptovoxels.com/api/islands.json' > CryptoVoxelsArchive/islands.json ;
          cat CryptoVoxelsArchive/parcels.json | jq '.parcels | .[] | .id' | while read id ;
          do 
            echo "Downloading land parcel info $id..."
            curl -s "https://www.cryptovoxels.com/grid/parcels/$id" > CryptoVoxelsArchive/parcels/$id.json
          done
          echo "Creating zip." ;
          zip -r -q CryptoVoxels-latest-archive.zip CryptoVoxelsArchive ;
          echo "Deploying archive to Arweave." ;
